services:
  gnt_db:
    image: postgres:latest
    container_name: gnt_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - gnt_network

  gnt_pgadmin:
    image: dpage/pgadmin4
    container_name: gnt_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - gnt_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - gnt_network

volumes:
  pgadmin_data:

networks:
  gnt_network:
    external: true
